### 시동 ON 정보 전달(성공)
POST localhost:8081/api/v1/vehicles/key-on
Content-Type: application/json

{
  "mdn": "1010101010",
  "tid": "TID001",
  "mid": "1",
  "pv": "1",
  "did": "1",
  "onTime": "20250110202211",
  "offTime": "20240109112233",
  "gcd": "A",
  "lat": "37123456",
  "lon": "127123456",
  "ang": "90",
  "spd": "50",
  "sum": "10000"
}
