server:
  port: 8080
  forward-headers-strategy: FRAMEWORK

spring:
  application:
    name: monicar-control-center

  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

websocket:
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS}

springdoc:
  swagger-ui:
    enabled: false