server:
  port: 8081

spring:
  application:
    name: monicar-control-center

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      jdbc:
        time_zone: Asia/Seoul

  sql:
    init:
      mode: never
      schema-locations: classpath:/schema/init-schema.sql
      data-locations: classpath:/data/init-data.sql
  data:
    web:
      pageable:
        one-indexed-parameters: true

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${ACCESS_EXPIRATION}
    refresh: ${REFRESH_EXPIRATION}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:}