server:
  port: 8081

spring:
  application:
    name: monicar-control-center

  config:
    activate:
      on-profile: local
  elasticsearch:
    uris: ${ELASTIC_SEARCH_URI}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      schema-locations: classpath:/schema/init-schema.sql
      data-locations: classpath:/data/init-data.sql
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${ACCESS_EXPIRATION}
    refresh: ${REFRESH_EXPIRATION}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:}

cookie:
  domain: ${COOKIE_DOMAIN}

logging:
  config: classpath:logback-spring-dev.xml
  file:
    path: ${user.dir}/logs
swagger:
  server:
    prod-url: ${PROD_URL}
    dev-url: ${DEV_URL}
alarm:
  secret-key: ${ALARM_SECRET}
security:
  secret-key: ${SESSION_SECRET}
  rememberme:
    cookieName: ${REMEMBERME_NAME}
    cookieDomain: ${REMEMBERME_DOMAIN}