server:
  port: 8081

spring:
  application:
    name: monicar-control-center

  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      schema-locations: classpath:/schema/init-schema.sql
      data-locations: classpath:/data/init-data.sql
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/monicar_db
    username: local_user
    password: local_password

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${ACCESS_EXPIRATION}
    refresh: ${REFRESH_EXPIRATION}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:}