server:
  port: 8083
  forward-headers-strategy: FRAMEWORK

spring:
  application:
    name: monicar-control-center

  config:
    activate:
      on-profile: dev
  elasticsearch:
    uris: ${ELASTIC_SEARCH_URI}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  sql:
    init:
      mode: never
      schema-locations: classpath:/schema/init-schema.sql
      data-locations: classpath:/data/init-data.sql
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6380
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:}

cookie:
  domain: ${COOKIE_DOMAIN}

logging:
  config: classpath:logback-spring-dev.xml
  file:
    path: /var/log/app-logs
swagger:
  server:
    prod-url: ${PROD_URL}
    dev-url: ${DEV_URL}
alarm:
  secret-key: ${ALARM_SECRET}
security:
  secret-key: ${SESSION_SECRET}
  rememberme:
    cookieName: ${REMEMBERME_NAME}
    cookieDomain: ${REMEMBERME_DOMAIN}