server:
  port: 8080

spring:
  application:
    name: monicar-collector

    #  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/monicar?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    username: root
    #    password:
  datasource:
    url: jdbc:mysql://localhost:3306/monicar_db
    username: local_user
    password: local_password


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
    properties:
      spring:
        json:
          trusted-packages: "*"
    listener:
      concurrency: 1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1


logging:
  level:
    org.hibernate.SQL: debug