services:
  container1:
    container_name: tomato
    build:
      context: ../
      dockerfile: simulation/Dockerfile
    ports:
      - "8091:8091"
    environment:
      - SPRING_PROFILES_ACTIVE=tomato

  container2:
    container_name: banana
    build:
      context: ../
      dockerfile: simulation/Dockerfile
    ports:
      - "8092:8092"
    environment:
      - SPRING_PROFILES_ACTIVE=banana

  container3:
    container_name: apple
    build:
      context: ../
      dockerfile: simulation/Dockerfile
    ports:
      - "8093:8093"
    environment:
      - SPRING_PROFILES_ACTIVE=apple