package org.common.dto;

import lombok.Getter;

@Getter
public enum ResponseCode {
	SUCCESS("000"),
	INVALID_ACCESS_PATH("100"),
	WRONG_APPROACH("101"),
	CONTENT_TYPE_ERROR("102"),
	CONTENT_LENGTH_ERROR("103"),
	ACCEPT_ERROR("104"),
	CACHE_CONTROL_ERROR("105"),
	ACCEPT_ENCODING_ERROR("106"),
	TIMESTAMP_ERROR("107"),
	TUID_ERROR("108"),
	MISSING_KEY_VERSION("109"),
	NOT_JSON_HEADER_TYPE("110"),
	MISSING_TOKEN("200"),
	INVALID_TOKEN("201"),
	UNUSABLE_TOKEN("202"),
	PROTOCOL_FORMAT_ERROR("300"),
	REQUIRED_PARAMETER_ERROR("301"),
	NO_SEARCH_RESULTS("302"),
	DECRYPTION_ERROR("303"),
	MISMATCHED_MDN("304"),
	DATA_PROCESSING_ERROR("400"),
	UNDEFINED_ERROR("500");

	private final String code;

	ResponseCode(String code) {
		this.code = code;
	}

}
